# Generated by Django 5.0.2 on 2024-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsListed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_img', models.ImageField(upload_to='uploads/')),
                ('company_name', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('job_employment_type', models.CharField(max_length=255)),
                ('job_salary', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
