# Generated by Django 5.0.3 on 2024-03-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_street',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
