# Generated by Django 5.0.3 on 2024-03-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobpost_job_street'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
