# Generated by Django 4.2.6 on 2024-03-15 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_img',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='ownerId',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_employment_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(max_length=30),
        ),
    ]
