# Generated by Django 4.2.6 on 2024-03-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_jobpost_company_img_jobpost_ownerid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_name',
        ),
    ]
