# Generated by Django 4.2.6 on 2024-03-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_jobpost_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='ownerId',
        ),
    ]
