# Generated by Django 4.2.6 on 2024-03-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_jobpost_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='ownerId',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
