# Generated by Django 4.2.6 on 2024-03-26 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jobapplication_jobpost_applicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='company_overview',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='key_responsibilities',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='qualifications',
        ),
    ]
