# Generated by Django 4.2.6 on 2024-03-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jobapplieduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobAppliedUser',
        ),
    ]
