# Generated by Django 4.2.6 on 2024-04-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='jobs',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.jobpost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories'),
        ),
    ]
