# Generated by Django 4.2.6 on 2024-04-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notifications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
