# Generated by Django 4.2.6 on 2024-04-23 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_user'),
        ('api', '0017_delete_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='doc_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='documents.document'),
            preserve_default=False,
        ),
    ]
