# Generated by Django 5.0.2 on 2024-02-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobslisted_job_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslisted',
            name='job_location',
            field=models.CharField(choices=[('Remote only, anywhere', 'Remote only, anywhere'), ('Hybrid', 'Hybrid'), ('Office /on Spot/', 'Office /on Spot/')], default='Office', max_length=30),
        ),
    ]
