# Generated by Django 5.0.2 on 2024-02-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobslisted_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslisted',
            name='company_img',
            field=models.ImageField(blank=True, null=True, upload_to='companies/post_picture'),
        ),
    ]
