# Generated by Django 5.0.2 on 2024-02-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobslisted_company_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobslisted',
            name='company_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobslisted',
            name='job_category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobslisted',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobslisted',
            name='key_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobslisted',
            name='preferred_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobslisted',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
