# Generated by Django 5.0.2 on 2024-02-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobslisted_company_overview_jobslisted_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslisted',
            name='company_overview',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='jobslisted',
            name='job_description',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='jobslisted',
            name='key_responsibilities',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='jobslisted',
            name='preferred_skills',
            field=models.TextField(blank=True, default='none', null=True),
        ),
        migrations.AlterField(
            model_name='jobslisted',
            name='qualifications',
            field=models.TextField(blank=True, default='none', null=True),
        ),
    ]
