# Generated by Django 5.0.2 on 2024-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobslisted_company_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobslisted',
            old_name='job_location',
            new_name='job_city',
        ),
        migrations.AddField(
            model_name='jobslisted',
            name='job_country',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
