# Generated by Django 4.2.6 on 2024-03-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_job_location_jobslisted_job_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobslisted',
            name='job_employment_type',
        ),
        migrations.RemoveField(
            model_name='jobslisted',
            name='job_type',
        ),
    ]
