# Generated by Django 4.2.6 on 2024-03-05 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_remove_jobslisted_job_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobslisted',
            name='job_employment_type',
            field=models.CharField(choices=[('Remote_only', 'Remote only'), ('Hybrid', 'Hybrid'), ('Office', 'Office /on Spot/')], default='Office', max_length=30),
        ),
        migrations.AddField(
            model_name='jobslisted',
            name='job_type',
            field=models.CharField(choices=[('Full_time', 'Full time'), ('Part_time', 'Part time'), ('Internship', 'Internship'), ('Temporary', 'Temporary'), ('For_students', 'For students'), ('Flexible', 'Flexible')], default='Full Time', max_length=30),
        ),
    ]
