# Generated by Django 4.2.6 on 2024-03-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0010_jobslisted_job_employment_type_jobslisted_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobslisted',
            name='ownerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
