# Generated by Django 4.2.6 on 2024-03-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0011_jobslisted_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobslisted',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
