# Generated by Django 4.2.6 on 2024-03-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0007_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
