# Generated by Django 4.2.6 on 2024-03-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0010_remove_user_city_remove_user_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='universal_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
