# Generated by Django 4.2.6 on 2024-03-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0012_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
