# Generated by Django 4.2.6 on 2024-03-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0014_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
